### ISSUE TITLE
This new library doesn't work for ESP8266 boards.

### ISSUE THREAD

**Issue by akshaywani8** [ErfanDL/ESPOTADASH_Library#4]
When I try to upload the example code in the ESP8266 boards like: 
1) NodeMCU 1.0 (ESP-12E) module
2) Generic ESP8266 module
The code never compiles and I get the following error:
1) For NodeMCU 1.0 (ESP-12E) module
![image](https://github.com/ErfanDL/ESPOTADASH_Library/assets/161835385/a34ca141-789e-414f-b152-6b61016778aa)

2) For Generic ESP8266 module
![image](https://github.com/ErfanDL/ESPOTADASH_Library/assets/161835385/0c015881-6055-45c4-bf85-188ad82aa193)

But for ESP32 boards, the code gets compiled and works perfectly fine.

**Please make it work for ESP8266 boards as well. That'll be great! Thanks in Advance!**

**Comment by ErfanDL** [comment]
> When I try to upload the example code in the ESP8266 boards like:
> 
>     1. NodeMCU 1.0 (ESP-12E) module
> 
>     2. Generic ESP8266 module
>        The code never compiles and I get the following error:
> 
>     3. For NodeMCU 1.0 (ESP-12E) module
>        ![image](https://private-user-images.githubusercontent.com/161835385/310421632-a34ca141-789e-414f-b152-6b61016778aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mzc0MjMsIm5iZiI6MTcwOTczNzEyMywicGF0aCI6Ii8xNjE4MzUzODUvMzEwNDIxNjMyLWEzNGNhMTQxLTc4OWUtNDE0Zi1iMTUyLTZiNjEwMTY3NzhhYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxNDU4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjNmMTgyZTJkOWE3MzE5ZGE5NmQ1MjYwZDJkY2E5YjQ0MzgxOTExMWI5YjE2MjNlOGFhMTNjZWI1YzdkMTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kIrdrqYr1LUoOAxK7V_SO67z3p7_6bT-UPG3x5FCFJs)
> 
>     4. For Generic ESP8266 module
>        ![image](https://private-user-images.githubusercontent.com/161835385/310423156-0c015881-6055-45c4-bf85-188ad82aa193.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3Mzc0MjMsIm5iZiI6MTcwOTczNzEyMywicGF0aCI6Ii8xNjE4MzUzODUvMzEwNDIzMTU2LTBjMDE1ODgxLTYwNTUtNDVjNC1iZjg1LTE4OGFkODJhYTE5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxNDU4NDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMGY5NWM5ZjdiZTg2YWI0MjYwZmViNWM3MzI3M2E2MWU0ZTVjMjlkNzgxZmYxMTU4N2ViYTc4NmZlMmQ1M2YxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wxVSK9LezHLHYUe90uAyVBFJPdKDwvDY0RLv0ZAwGwQ)
> 
> 
> But for ESP32 boards, the code gets compiled and works perfectly fine.
> 
> **Please make it work for ESP8266 boards as well. That'll be great! Thanks in Advance!**

Compiled without any error ! please install library correctly 

![com](https://github.com/ErfanDL/ESPOTADASH_Library/assets/14868771/0e4f59c9-a6db-412a-981f-0aa496d1c7b8)

**Comment by akshaywani8** [comment]
I downloaded the zipped library since I don't use Git Bash or CLI.
Does it make a difference?

Because it is a zip file, so all the files get downloaded without any interruptions or missing files.

When I used this library for the very first time, it worked on all the boards that I uploaded it to: NodeMCU 1.0, Generic ESP8266, ESP32-WROOM DA, ModeMCU-32S. It worked on all the boards.

Later it didn't work for Generic ESP8266 and NodeMCU 1.0 boards. 

Do I need to download additional libraries/files to make it work on ESP8266 based boards?

**Comment by akshaywani8** [comment]
Ok, so I downloaded only the folder named 'ESPOTADASH' and now the code is successfully getting compiled every single time.
Ergo, the OTA feature is working on the following boards: NodeMCU 1.0 (ESP-12E module) and Generic ESP8266 module.

But it is not working on ESP32 boards now! I've already downloaded 'ESP32OTAUpdater' folder. But no success yet. 
Is there any other library needed to install for this?

**Comment by ErfanDL** [comment]
> Ok, so I downloaded only the folder named 'ESPOTADASH' and now the code is successfully getting compiled every single time. Ergo, the OTA feature is working on the following boards: NodeMCU 1.0 (ESP-12E module) and Generic ESP8266 module.
> 
> But it is not working on ESP32 boards now! I've already downloaded 'ESP32OTAUpdater' folder. But no success yet. Is there any other library needed to install for this?

you need to put ESP32OTAUpdater folder to arduino library folder.

**Comment by akshaywani8** [comment]
> > Ok, so I downloaded only the folder named 'ESPOTADASH' and now the code is successfully getting compiled every single time. Ergo, the OTA feature is working on the following boards: NodeMCU 1.0 (ESP-12E module) and Generic ESP8266 module.
> > But it is not working on ESP32 boards now! I've already downloaded 'ESP32OTAUpdater' folder. But no success yet. Is there any other library needed to install for this?
> 
> you need to put ESP32OTAUpdater folder to arduino library folder.

I downloaded the folder named 'ESP32OTAUpdater' and saved it in my Arduino/libraries/.
Then I opened the example sketch and selected 'ESP32-WROOM-DA module' board to compile. Now it is displaying these error messages:
 
![image](https://github.com/ErfanDL/ESPOTADASH_Library/assets/161835385/1a367285-a74b-42b0-9f28-03607195559e)

Do I need to install some other libraries?

**Comment by ErfanDL** [comment]
you are using multiple HTTP clients library's. These conflict with each other.

**Comment by akshaywani8** [comment]
> you are using multiple HTTP clients library's. These conflict with each other.

ESPOTADASH.cpp:116:41: error: 'ESP32httpUpdate' was not declared in this scope
               t_httpUpdate_return ret = ESP32httpUpdate.update(String(serverAddress) + "/upload/" + urlEncode(hostName) + "_firmware.bin", firmwareVersion); // Use urlEncode() function here
                                         ^~~~~~~~~~~~~~~

Does the .cpp file needs some changes? Because it is suggesting the following:
ESPOTADASH.cpp:116:41: note: suggested alternative: 'ESP32shttpUpdate'

**Comment by akshaywani8** [comment]
![image](https://github.com/ErfanDL/ESPOTADASH_Library/assets/161835385/927577cf-ec29-45bb-ac31-478698320617)


After making the changes in the main file 'ESPOTADASH.cpp' as per the suggested alternative, now the sketch got compiled (as seen in the above screenshot) for ESP32-WROOM-DA module.

Ergo, the library is getting compiled for both ESP8266 boards as well as ESP32 boards.

Thanks for the help!
